version: '2.1'
services:
  web:
    build: .
    command: bundle exec unicorn -p 4567 -c ./unicorn.rb
    env_file:
       - .env
    ports:
      - "4567:4567"
    links:
      - redis

  worker:
    build: .
    command: env TERM_CHILD=1 QUEUES=* bundle exec rake jobs:work
    env_file:
       - .env
    links:
       - redis

  redis:
    image: redis
    sysctls:
      - net.core.somaxconn=1024
    hostname: redis
    ports:
      - "6379:6379"
    restart: always

